add docker secret check

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -24,6 +24,18 @@ jobs:
       - name: Build JAR
         run: ./gradlew clean bootJar
 
+      - name: Check Docker secrets"
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+            echo "DOCKER_USERNAME is missing"
+            exit 1
+          fi
+          if [ -z "${{ secrets.DOCKER_SECRET }}" ]; then
+            echo "DOCKER_SECRET is missing"
+            exit 1
+          fi
+          echo "Docker secrets are present"
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
